# Source Analyzer Global Configuration
# 이 파일은 모든 Phase에 공통으로 적용되는 전역 설정을 정의합니다.

# 프로젝트 설정
# 분석 대상 프로젝트의 기본 정보를 정의합니다.
project:
  default_project_name: "sampleSrc" # 기본 프로젝트 이름
  # 프로젝트별 경로 템플릿 ({project_name}은 실제 프로젝트명으로 치환됨)
  paths:
    base_dir: "./project/{project_name}"              # 프로젝트 기본 디렉토리
    source_dir: "./project/{project_name}/src"        # 소스 코드 디렉토리
    db_schema_dir: "./project/{project_name}/db_schema" # DB 스키마 CSV 디렉토리
    data_dir: "./project/{project_name}/data"         # 프로젝트별 분석 데이터 저장 디렉토리
    output_dir: "./output/{project_name}"             # 프로젝트별 출력 디렉토리 (사용자가 결과물 확인)
    visualize_dir: "./output/{project_name}/visualize" # 시각화 출력 디렉토리
    log_dir: "./output/{project_name}/logs"           # 프로젝트별 분석 로그

# 데이터베이스 설정
# Source Analyzer가 분석 결과를 저장하고 관리하는 데 사용하는 데이터베이스를 설정합니다.
database:
  # 글로벌 데이터베이스 (phase1 메타데이터, 설정, 통계 등)
  global:
    type: sqlite
    sqlite:
      path: "./data/metadata.db"  # 글로벌 메타데이터 (phase1 자체 정보)
      wal_mode: true
  
  # 프로젝트별 데이터베이스 (각 프로젝트의 분석 결과)
  project:
    type: sqlite
    sqlite:
      path: "./project/{project_name}/data/metadata.db"  # 프로젝트별 분석 결과
      wal_mode: true
  
  # Oracle 설정 (필요시 글로벌/프로젝트별 동일하게 적용)
  oracle:
    host: "localhost"           # Oracle 데이터베이스 호스트
    port: 1521                  # Oracle 데이터베이스 포트
    service_name: "orcl"        # Oracle 서비스 이름
    username: "analyzer"        # Oracle 사용자 이름
    password: "password"        # Oracle 비밀번호

# 벡터 스토어 설정
# LLM 기반 분석을 위한 벡터 임베딩 저장소를 설정합니다.
vector_store:
  type: faiss  # 사용하고자 하는 벡터 스토어 유형 (현재 faiss만 지원)
  faiss:
    index_path: "./project/{project_name}/data/faiss.index"  # FAISS 인덱스 파일 경로 (프로젝트별)
    model_name: "BAAI/bge-m3"         # 임베딩 모델 이름 (다국어 지원)
    dimension: 1024                   # 임베딩 벡터 차원

# 로깅 설정
# 애플리케이션의 로깅 동작을 설정합니다.
logging:
  level: "DEBUG"            # 로깅 레벨 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  max_size: "100MB"         # 로그 파일 최대 크기
  backup_count: 3           # 보관할 백업 로그 파일 수
  
  # 글로벌 로그 (phase1 자체 동작 로그)
  global_log: "./logs/analyzer.log"  # phase1 시스템 로그
  
  # 프로젝트별 로그 (사용자가 확인 가능한 위치)
  project_log: "./output/{project_name}/logs/analysis.log"  # 프로젝트별 분석 로그

# 웹 서버 (백엔드) 설정
# 웹 대시보드 백엔드 서버의 동작을 설정합니다.
server:
  host: "127.0.0.1"         # 서버가 바인딩될 IP 주소
  port: 8000                # 서버가 수신 대기할 포트 번호
  debug: true               # 디버그 모드 활성화 여부
  reload: false             # 코드 변경 시 서버 자동 재시작 여부 (개발 환경에서 유용)
  api_prefix: "/api"        # API 엔드포인트 접두사
  cors:                     # CORS(Cross-Origin Resource Sharing) 설정
    enabled: true           # CORS 활성화 여부
    allow_origins: ["*"]    # 허용할 Origin 목록 (예: ["http://localhost:3000", "http://127.0.0.1:3000"])
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"] # 허용할 HTTP 메서드
    allow_headers: ["*"]    # 허용할 HTTP 헤더
    credentials: false      # 자격 증명(쿠키, HTTP 인증) 허용 여부
    expose_headers: []      # 클라이언트에 노출할 헤더 목록
  log_file: "./logs/backend.log" # 백엔드 로그 파일 경로 (공통, 생략 시 상위 로깅 설정 따름)
  log_level: "DEBUG"        # 백엔드 로깅 레벨 (생략 시 상위 로깅 설정 따름)
  static:                   # 정적 파일 서빙 설정
    enabled: false          # 정적 파일 서빙 활성화 여부
    folder: "./web-dashboard/frontend/dist" # 정적 파일이 위치한 폴더 경로
    url_path: "/static"     # 정적 파일에 접근할 URL 경로