# Source Analyzer Configuration
# Phase 1: Metadata Generation Configuration

# Database Configuration
database:
  type: sqlite  # sqlite for dev, oracle for prod
  sqlite:
    path: "./data/metadata.db"
    wal_mode: true
  oracle:
    host: "localhost"
    port: 1521
    service_name: "orcl"
    username: "analyzer"
    password: "password"

# Vector Store Configuration  
vector_store:
  type: faiss
  faiss:
    index_path: "./data/faiss.index"
    model_name: "BAAI/bge-m3"  # Multi-language embedding model
    dimension: 1024
    
# Parser Configuration
parsers:
  java:
    enabled: true
    parser_type: "javaparser"  # javaparser or tree-sitter
    java_version: 8
    
  jsp:
    enabled: true
    parser_type: "antlr"
    
  mybatis:
    enabled: true
    parser_type: "jsqlparser"
    
  sql:
    enabled: true
    parser_type: "jsqlparser"
    oracle_dialect: true
    
  tree_sitter:
    enabled: false  # for future use
    languages: ["java", "javascript", "typescript", "python"]

# LLM Configuration (for enrichment)
llm:
  enabled: true
  base_model: "qwen2.5-7b"
  fallback_model: "qwen2.5-32b"
  vllm_endpoint: "http://localhost:8000"
  temperature: 0.0
  max_tokens: 2048
  
# Embedding Models
embedding:
  models:
    - name: "BAAI/bge-m3"
      type: "multilingual"
      max_length: 8192
      batch_size: 32
    - name: "jhgan00/ko-sentence-transformers" 
      type: "korean"
      max_length: 512
      batch_size: 16

# Processing Configuration
processing:
  max_workers: 4
  chunk_size: 512
  chunk_overlap: 50
  confidence_threshold: 0.5
  
# Output Configuration
output:
  metadata_only: true  # No source code storage
  include_line_ranges: true
  include_confidence: true
  log_enrichment: true

# File Patterns
file_patterns:
  include:
    - "**/*.java"
    - "**/*.jsp" 
    - "**/*.xml"
    - "**/*.properties"
  exclude:
    - "**/target/**"
    - "**/build/**"
    - "**/test/**"
    - "**/.git/**"

# DB Schema Files
db_schema:
  required_files:
    - "ALL_TABLES.csv"
    - "ALL_TAB_COLUMNS.csv" 
    - "ALL_TAB_COMMENTS.csv"
    - "ALL_COL_COMMENTS.csv"
    - "PK_INFO.csv"
  path_template: "./PROJECTS/{project_name}/DB_SCHEMA/"

# Logging
logging:
  level: "INFO"
  file: "./logs/analyzer.log"
  max_size: "100MB"
  backup_count: 3