# Create MetaDB 설정 파일
# 신규입사자 지원을 위한 최적화된 메타정보 생성 시스템

# 프로젝트 기본 설정
project:
  name: ""  # 프로젝트명 (실행 시 --project-name으로 지정)
  source_path: "../project/{project_name}/src"  # 소스 경로 (상대경로)
  db_schema_path: "../project/{project_name}/db_schema"  # DB 스키마 경로

# 데이터베이스 설정
database:
  output_db: "../project/{project_name}/metadata_optimized.db"  # 출력 메타DB
  connection_timeout: 30  # 연결 타임아웃
  query_timeout: 60  # 쿼리 타임아웃
  backup_enabled: true  # 백업 활성화
  backup_path: "../project/{project_name}/backup"  # 백업 경로

# LLM 설정
llm:
  enabled: false  # LLM 기능 사용 여부
  model: "gpt-3.5-turbo"  # 사용할 LLM 모델
  api_key: "${LLM_API_KEY}"  # API 키 (환경변수에서 가져옴)
  max_tokens: 500  # 최대 토큰 수
  timeout: 30  # 타임아웃 (초)
  
# SQL 분석 설정
sql_analysis:
  use_llm_for_complex_queries: true  # 복잡한 쿼리에 LLM 사용
  complexity_threshold: 3  # 조인 수가 3개 이상일 때 LLM 사용
  default_owner: "APP_USER"  # FROM 절에 owner가 없는 경우 기본값
  
# 외부 청크 처리 설정
external_chunks:
  default_owner: "EXTERNAL"  # 외부 청크의 기본 owner
  auto_create: true  # 외부 청크 자동 생성 여부
  confidence_threshold: 0.5  # 외부 청크 신뢰도 임계값
  
# 요약 생성 설정
summarization:
  generate_for_classes: true  # 클래스 요약 생성
  generate_for_methods: true  # 메서드 요약 생성
  generate_for_sql_units: true  # SQL 단위 요약 생성
  summary_types:  # 생성할 요약 유형
    - "business_purpose"  # 비즈니스 목적
    - "technical_summary"  # 기술적 내용
    - "learning_guide"  # 학습 가이드

# 성능 최적화 설정
performance:
  batch_size: 100  # 배치 처리 크기
  max_workers: 4  # 최대 워커 수
  memory_limit: "1GB"  # 메모리 제한
  
# 로깅 설정
logging:
  level: "INFO"  # 로그 레벨 (DEBUG, INFO, WARNING, ERROR)
  file: "logs/create_metadb_{timestamp}.log"  # 로그 파일 경로
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
